version: '3'
networks:
  front:
    driver: bridge
  back:
    driver: bridge

services:
  nginx:
    container_name: nginx
    image: nginx:1.13
    networks:
      - front
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - service

  mysql:
    container_name: mysql
    image: "mysql/mysql-server:5.7"
    networks:
      - back
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
    expose:
      - "3306"
    volumes:
      - ./mysql:/var/lib/mysql
    restart: always

  redis:
    container_name: redis
    image: "redis:alpine"
    networks:
      - back
    expose:
      - "6379"
    restart: always

  service:
    container_name: back-end
    restart: always
    image: "southestsoul/docker-compose"
    networks:
      - front
      - back
    expose:
      - "8080"
    depends_on:
      - mysql
      - redis

#  service:
#    container_name: back-end
#    restart: always
#    build:
#      context: ./app
#      dockerfile: Dockerfile
#    networks:
#      - front
#      - back
#    expose:
#      - "8080"
#    depends_on:
#      - mysql
#      - redis

